name: Deploy AWS EC2 with Terraform and Install Software

on:
  workflow_dispatch:
    inputs:
      vnc_username:
        description: "Enter VNC Username"
        required: true
      vnc_password:
        description: "Enter VNC Password"
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy EC2 Instance and Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Get EC2 Public IP
        id: ec2_ip
        run: |
          PUBLIC_IP=$(terraform -chdir=terraform output -raw instance_public_ip)
          echo "EC2_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Upload install.sh to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

          scp -o StrictHostKeyChecking=no -i key.pem install.sh ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/install.sh
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_PUBLIC_IP "chmod +x /home/ubuntu/install.sh"

      - name: Run install.sh on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_PUBLIC_IP \
            "/home/ubuntu/install.sh '${{ github.event.inputs.vnc_username }}' '${{ github.event.inputs.vnc_password }}'"
